from contourusv import detect_contours

def test_detect_contour():
    # TODO: Use get_usvseg("rat_distressed") to download this dataset...
    # TODO: Test detect_contour on this example file...
    pass
